# .gitlab-ci.yml
image: alpine:latest
pages:
  stage: deploy
  script:
    - apk add --no-cache bash
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main
